# Generated by Django 3.1.1 on 2020-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201005_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
