# Generated by Django 3.1.1 on 2020-10-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201006_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
