# Generated by Django 3.1.1 on 2020-10-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myosu',
            fields=[
                ('mid', models.AutoField(db_column='mid', primary_key=True, serialize=False)),
                ('data', models.TextField(db_column='data')),
                ('round', models.IntegerField(db_column='round')),
            ],
            options={
                'db_table': 'myosu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='omokgame',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('data', models.TextField(db_column='data')),
                ('auid', models.IntegerField(db_column='auid')),
                ('turn', models.IntegerField(db_column='turn')),
                ('date', models.DateTimeField(db_column='date')),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('rid', models.AutoField(db_column='rid', primary_key=True, serialize=False)),
                ('uid', models.IntegerField(db_column='uid')),
                ('att_turn', models.IntegerField(db_column='att_turn', default=0)),
                ('level', models.IntegerField(db_column='level')),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrickSolving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game1', models.BooleanField(default=False)),
                ('game2', models.BooleanField(default=False)),
                ('game3', models.BooleanField(default=False)),
                ('game4', models.BooleanField(default=False)),
                ('game5', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
