# Generated by Django 3.1.1 on 2020-10-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omok_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myosu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='omokgame',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
