# Generated by Django 3.1.1 on 2020-10-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok_game', '0002_auto_20201005_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tricksolving',
            name='game1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tricksolving',
            name='game2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tricksolving',
            name='game3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tricksolving',
            name='game4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tricksolving',
            name='game5',
            field=models.IntegerField(default=0),
        ),
    ]
