# Generated by Django 3.1.1 on 2020-10-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok_game', '0003_auto_20201006_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tricksolving',
            name='user',
            field=models.IntegerField(),
        ),
    ]
