# Generated by Django 3.1.1 on 2020-10-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok_game', '0004_auto_20201007_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tricksolving',
            old_name='game1',
            new_name='game1_1',
        ),
        migrations.RenameField(
            model_name='tricksolving',
            old_name='game2',
            new_name='game1_2',
        ),
        migrations.RenameField(
            model_name='tricksolving',
            old_name='game3',
            new_name='game1_3',
        ),
        migrations.RenameField(
            model_name='tricksolving',
            old_name='game4',
            new_name='game1_4',
        ),
        migrations.RenameField(
            model_name='tricksolving',
            old_name='game5',
            new_name='game1_5',
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game2_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game2_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game2_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game2_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game2_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game3_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game3_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game3_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game3_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tricksolving',
            name='game3_5',
            field=models.IntegerField(default=0),
        ),
    ]
