# Generated by Django 3.1.1 on 2020-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok_game', '0005_auto_20201007_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('win', models.IntegerField(default=0)),
                ('ailevel', models.IntegerField()),
                ('turn', models.IntegerField()),
                ('game', models.CharField(max_length=1000)),
                ('user', models.IntegerField()),
            ],
        ),
    ]
