# Generated by Django 3.1.1 on 2020-10-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omok_game', '0006_recode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recode',
            name='title',
        ),
    ]
